language: node_js
node_js:
- stable
sudo: false
script:
- npm install
- npm run compile
- npm run make-components
branches:
  only:
  - "/^\\d+\\.\\d+/"
deploy:
  provider: npm
  email: manager@mathjax.org
  api_key:
    secure: iiJYaydsd6nypSMgjvQiTYIy+YF/oil5fqfVLmMkAQtykAqE5oS/HcJ6QxQa8DKHQCmNNhmUqMnD7H5jVhXGcbhEcx7dNxr7pXkrY2Vkyj8voYFIfZ05rwfaojQQPlPdrkwiLmAcUnz1v9gP20M6uVJrhVpBSe4bfHxSHbSUBjlRu4md8fXyA9cLJ3hu/QHV2ahjRDHL+axklCH8YFMW2bN7IRYALUaFeN6gZFWQvq6A4gT1zaFo0yTsej5z+PmyvDHYGzI1KfUioNa81KMWvSMIkRooJes2JrDFdo4HYXgYhZ/wb+7FLOJGeLLQejfQiVw+MS+7R+C6Ss/TcxddeBGg+x9+pZY4AvnVjuWfYW7WSh+iMZ1ujFE3xhqjVUI6WpowSfLK2lguY/8AZ1hKuWxnWw/UwCGcy6qOG0HMyE05mkl+VvPMITckkkeM/an4k7PeR+DY9L25Imp0jmpCyfk72KXMAEgVLAjnsy+l0EnZWK7oeYzDwEaw8HdOCmKKraRYFSetbqC+25g1iKc8ylTs1IxN7HXo0e0dTGSxwtU14L26GMHrC2pVsDdeR7+b5ll0C/6kevK794eQpzSEM50Addb1+fUJ3bn1y22H7OaglnJYxfuP44AYTENOn3fDJrIgcVG/yp273MImSYZiXL+xQBK8ZPEG5z36sH5/iAI=
  on:
    tags: true
  skip_cleanup: true
